version: '3'

tasks:
  default:
    cmds:
      - task: deploy
  build:
    cmds:
      - go build -o bin/task
  deploy:
    deps: [build]
    cmds:
      - scp bin/task student@brandon-gl-serveur.eddi.cloud:/home/student/
      - ssh student@brandon-gl-serveur.eddi.cloud "chmod u+x task"